# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
BruensHelloBundle:
   resource: "@BruensHelloBundle/Resources/config/routing.yml"
   prefix: /