parameters:
#    bruens_hello.example.class: Bruens\HelloBundle\Example

services:
#    bruens_hello.example:
#        class: %bruens_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
